import Head from "next/head";
import {ReactElement} from "react";
import {DefaultLayout} from "../layouts/default";
import {NextPageWithLayout} from "./_app";

const Home: NextPageWithLayout = () => {
    return (
        <>
            <Head>
                <title>Learning React + Next.js using TypeScript</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            {/* <Hero /> */}
        </>
    );
};

Home.getLayout = function getLayout(page: ReactElement) {
    return <DefaultLayout>{page}</DefaultLayout>;
};

export default Home;
