import Head from "next/head";
import {ReactElement} from "react";
import {DefaultLayout} from "@layouts/default";
import {NextPageWithLayout} from "pages/_app";
import Heading1 from "@components/h1";
import Codeblock from "@components/codeblock";

import Example1 from '@images/example-1.png';
import Image from "next/image";

const Page: NextPageWithLayout = () => {
    /*
    TS Example START
     */
    console.log("A valid javascript is valid typescript.");
    /*
    TS Example END
     */
    return (
        <>
            <Head>
                <title>Example - 01 - Getting started.</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            {/* <Hero /> */}
            <Heading1>Getting started examples</Heading1>
            <p>1. The following code prints a message in the console of the browser.</p>
            
        </>
    );
};

Page.getLayout = function getLayout(page: ReactElement) {
    return <DefaultLayout>{page}</DefaultLayout>;
};

export default Page;
